/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'public'}],
  // api: [
  //   'api',
  //   'docusaurus-core',
  //   {
  //     type: 'autogenerated',
  //     dirName: 'api',
  //   },
  // ],
  tools: [
    {
      type: 'autogenerated',
      dirName: 'tools',
    },
  ],
  about: [
    {
      type: 'autogenerated',
      dirName: 'about',
    },
  ],
  backend: [
    {
      type: 'autogenerated',
      dirName: 'backend',
    },
  ],
  introduction: [
    {
      type: 'autogenerated',
      dirName: 'introduction',
    },
  ],
  frontend: [
    {
      type: 'autogenerated',
      dirName: 'frontend',
    },
  ],
  frontend_es6: [
    {
      type: 'autogenerated',
      dirName: 'frontend/es6',
    },
  ],

  mySidebar: [
    {
      type: 'category',
      label: 'Java 编程基础',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'public',
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  // docs: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'docs',
  //   },
  // ],
  // about: [
  //   // 'cli',
  //   {
  //     type: 'autogenerated',
  //     dirName: 'about',
  //   }
  // ]
};

module.exports = sidebars;
